name: flow_master
channels:
  - pkgs/main
dependencies:
  - attrs=24.3.0=py311haa95532_0
  - brotli-python=1.0.9=py311h5da7b33_9
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.9.9=haa95532_0
  - cachecontrol=0.12.11=py311haa95532_1
  - certifi=2025.10.5=py311haa95532_0
  - cffi=1.17.1=py311h827c3e9_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - cleo=2.1.0=py311haa95532_1
  - colorama=0.4.6=py311haa95532_0
  - crashtest=0.4.1=py311haa95532_1
  - cryptography=44.0.1=py311hbd6ee87_0
  - distlib=0.3.8=py311haa95532_0
  - dulwich=0.21.3=py311h2bbff1b_0
  - expat=2.7.1=h8ddb27b_0
  - filelock=3.17.0=py311haa95532_0
  - html5lib=1.1=pyhd3eb1b0_0
  - idna=3.7=py311haa95532_0
  - importlib-metadata=8.5.0=py311haa95532_0
  - importlib_metadata=8.5.0=hd3eb1b0_0
  - jaraco.classes=3.4.0=py311haa95532_0
  - jsonschema=4.25.0=py311haa95532_0
  - jsonschema-specifications=2023.7.1=py311haa95532_0
  - keyring=23.13.1=py311haa95532_0
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - lockfile=0.12.2=py311haa95532_0
  - more-itertools=10.3.0=py311haa95532_0
  - msgpack-python=1.1.1=py311h5da7b33_0
  - openssl=3.0.18=h543e019_0
  - packaging=25.0=py311haa95532_0
  - pexpect=4.9.0=py311haa95532_0
  - pip=25.2=pyhc872135_0
  - pkginfo=1.12.0=py311haa95532_0
  - platformdirs=2.5.2=py311haa95532_0
  - poetry=1.4.0=py311haa95532_0
  - poetry-core=1.5.1=py311haa95532_0
  - poetry-plugin-export=1.3.0=py311hfacae44_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pycparser=2.23=py311haa95532_0
  - pyopenssl=25.0.0=py311hb6ff9d5_0
  - pyproject_hooks=1.2.0=py311haa95532_0
  - pysocks=1.7.1=py311haa95532_0
  - python=3.11.13=h981015d_0
  - python-build=0.10.0=py311haa95532_0
  - python-installer=0.6.0=py311haa95532_0
  - pywin32-ctypes=0.2.2=py311haa95532_0
  - rapidfuzz=3.14.1=py311h885b0b7_0
  - referencing=0.30.2=py311haa95532_0
  - requests=2.32.5=py311haa95532_0
  - requests-toolbelt=0.9.1=pyhd3eb1b0_0
  - rpds-py=0.22.3=py311h636fa0f_0
  - setuptools=78.1.1=py311haa95532_0
  - shellingham=1.5.0=py311haa95532_0
  - six=1.17.0=py311haa95532_0
  - sqlite=3.50.2=hda9a48d_1
  - tk=8.6.15=hf199647_0
  - tomlkit=0.13.2=py311haa95532_0
  - trove-classifiers=2025.5.9.12=py311haa95532_0
  - typing_extensions=4.15.0=py311haa95532_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=1.26.19=py311haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - virtualenv=20.16.2=py311haa95532_0
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - webencodings=0.5.1=py311haa95532_1
  - wheel=0.45.1=py311haa95532_0
  - win_inet_pton=1.1.0=py311haa95532_0
  - xz=5.6.4=h4754444_1
  - zipp=3.21.0=py311haa95532_0
  - zlib=1.3.1=h02ab6af_0

prefix: "C:\\Users\\amand\\.local\\share\\mamba\\envs\\flow_master"
